# Generated by Django 3.0.6 on 2020-06-01 07:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optim_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfunction',
            name='relative_path',
            field=models.FilePathField(null=True, path='Optimization\\optim_project\\optim_app\\userfunctions'),
        ),
        migrations.CreateModel(
            name='ParameterInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.BooleanField()),
                ('lower_bound', models.FloatField()),
                ('upper_bound', models.FloatField()),
                ('user_function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optim_app.UserFunction')),
            ],
        ),
        migrations.CreateModel(
            name='optimization_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('min_or_max', models.FloatField()),
                ('param_info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('user_function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optim_app.UserFunction')),
            ],
        ),
    ]
