# Generated by Django 3.0.6 on 2020-06-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optim_app', '0002_auto_20200601_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfunction',
            name='relative_path',
            field=models.FilePathField(null=True, path='F:\\Bachelorsthesis\\Optimization\\optim_project\\optim_app\\userfunctions'),
        ),
    ]
