# Generated by Django 3.0.6 on 2020-06-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optim_app', '0003_auto_20200601_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfunction',
            name='relative_path',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
