# Generated by Django 3.0.6 on 2020-06-01 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optim_app', '0004_auto_20200601_2003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='optimization_history',
            new_name='OptimizationHistory',
        ),
        migrations.AlterField(
            model_name='parameterinfo',
            name='user_function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='param', to='optim_app.UserFunction'),
        ),
    ]
