# Generated by Django 3.0.6 on 2020-06-03 19:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optim_app', '0006_auto_20200601_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_function', models.BooleanField()),
                ('optimization_meth', models.CharField(max_length=64)),
                ('N', models.IntegerField()),
                ('optim_type', models.IntegerField()),
                ('value', models.FloatField()),
                ('param_func', django.contrib.postgres.fields.jsonb.JSONField()),
                ('param_optim', django.contrib.postgres.fields.jsonb.JSONField()),
                ('user_function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optim_app.UserFunction')),
            ],
        ),
        migrations.CreateModel(
            name='OptimizationParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_optim_meth', models.CharField(max_length=64)),
                ('meta_N', models.IntegerField()),
                ('meta_value', models.FloatField()),
                ('meta_param_optim', django.contrib.postgres.fields.jsonb.JSONField()),
                ('optim_func', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='optim_app.OptimizationFunction')),
                ('user_function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optim_app.UserFunction')),
            ],
        ),
        migrations.AlterField(
            model_name='parameterinfo',
            name='discrete_continuous',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='OptimizationHistory',
        ),
    ]
