# Generated by Django 3.0.6 on 2020-06-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optim_app', '0008_auto_20200607_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optimizationinfo',
            name='value',
        ),
        migrations.AddField(
            model_name='optimizationfunction',
            name='value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='optimizationparameters',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
